<template>
  <div class="py-8 px-8 bg-gray-900">
    <div class="flex flex-col items-center">
      <h2 class="text-2xl leading-none font-bold text-center pb-8 text-white">
        Explore countries
      </h2>
      <div v-if="countries" class="grid autogrid w-full">
        <!-- :to="{ name: 'country-country', params: { country: countryName } }" -->
        <nuxt-link
          v-for="countryName in countries"
          :to="'/country/' + countryName"
          :key="countryName"
          class="hover:text-gray-400 text-gray-500"
        >
          {{ countryName }}
        </nuxt-link>
      </div>
    </div>
  </div>
</template>

<script>
import { days_between, pickColor } from '../helpers'
import { format } from 'moment'

import { mapActions, mapGetters } from 'vuex'

export default {
  data() {
    return {
      countries: [
        'Afghanistan',
        'Albania',
        'Algeria',
        'Andorra',
        'Angola',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Benin',
        'Bhutan',
        'Bolivia',
        'Bosnia and Herzegovina',
        'Brazil',
        'Brunei',
        'Bulgaria',
        'Burkina Faso',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Central African Republic',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'Congo (Brazzaville)',
        'Congo (Kinshasa)',
        'Costa Rica',
        "Cote d'Ivoire",
        'Croatia',
        'Diamond Princess',
        'Cuba',
        'Cyprus',
        'Czechia',
        'Denmark',
        'Djibouti',
        'Dominican Republic',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini',
        'Ethiopia',
        'Fiji',
        'Finland',
        'France',
        'Gabon',
        'Gambia',
        'Georgia',
        'Germany',
        'Ghana',
        'Greece',
        'Guatemala',
        'Guinea',
        'Guyana',
        'Haiti',
        'Holy See',
        'Honduras',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran',
        'Iraq',
        'Ireland',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Korea, South',
        'Kuwait',
        'Kyrgyzstan',
        'Latvia',
        'Lebanon',
        'Liberia',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Madagascar',
        'Malaysia',
        'Maldives',
        'Malta',
        'Mauritania',
        'Mauritius',
        'Mexico',
        'Moldova',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Morocco',
        'Namibia',
        'Nepal',
        'Netherlands',
        'New Zealand',
        'Nicaragua',
        'Niger',
        'Nigeria',
        'North Macedonia',
        'Norway',
        'Oman',
        'Pakistan',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines',
        'Poland',
        'Portugal',
        'Qatar',
        'Romania',
        'Russia',
        'Rwanda',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'San Marino',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Singapore',
        'Slovakia',
        'Slovenia',
        'Somalia',
        'South Africa',
        'Spain',
        'Sri Lanka',
        'Sudan',
        'Suriname',
        'Sweden',
        'Switzerland',
        'Taiwan*',
        'Tanzania',
        'Thailand',
        'Togo',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Uganda',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom',
        'Uruguay',
        'US',
        'Uzbekistan',
        'Venezuela',
        'Vietnam',
        'Zambia',
        'Zimbabwe',
        'Dominica',
        'Grenada',
        'Mozambique',
        'Syria',
        'Timor-Leste',
        'Belize',
        'Laos',
        'Libya',
        'West Bank and Gaza',
        'Guinea-Bissau',
        'Mali',
        'Saint Kitts and Nevis',
        'Kosovo',
        'Burma',
        'MS Zaandam',
        'Botswana',
        'Burundi',
        'Sierra Leone',
        'Malawi',
        'South Sudan',
        'Western Sahara',
        'Sao Tome and Principe',
        'Yemen',
        'Comoros',
        'Tajikistan',
        'Lesotho'
      ]
    }
  }
}
</script>

<style>
.autogrid {
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
}
</style>
